name: 'dbt_reference_tables_demo'
version: '1.0.0'

profile: 'demo'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
docs-paths: ["docs"]

clean-targets:
  - "target"
  - "dbt_packages"
